[2024-03-18T04:29:31.737+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sftp_sync.sftp_sensor_task manual__2024-03-18T04:29:23.459078+00:00 [queued]>
[2024-03-18T04:29:31.923+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sftp_sync.sftp_sensor_task manual__2024-03-18T04:29:23.459078+00:00 [queued]>
[2024-03-18T04:29:31.951+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-03-18T04:29:32.064+0000] {taskinstance.py:2217} INFO - Executing <Task(SFTPSensor): sftp_sensor_task> on 2024-03-18 04:29:23.459078+00:00
[2024-03-18T04:29:32.100+0000] {standard_task_runner.py:60} INFO - Started process 102 to run task
[2024-03-18T04:29:32.128+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sftp_sync', 'sftp_sensor_task', 'manual__2024-03-18T04:29:23.459078+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/sftp_sync_between_source_and_target.py', '--cfg-path', '/tmp/tmp576hsrw2']
[2024-03-18T04:29:32.135+0000] {standard_task_runner.py:88} INFO - Job 25: Subtask sftp_sensor_task
[2024-03-18T04:29:32.694+0000] {task_command.py:423} INFO - Running <TaskInstance: sftp_sync.sftp_sensor_task manual__2024-03-18T04:29:23.459078+00:00 [running]> on host 78c95bc5c908
[2024-03-18T04:29:33.250+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sftp_sync' AIRFLOW_CTX_TASK_ID='sftp_sensor_task' AIRFLOW_CTX_EXECUTION_DATE='2024-03-18T04:29:23.459078+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-18T04:29:23.459078+00:00'
[2024-03-18T04:29:33.310+0000] {base.py:83} INFO - Using connection ID 'source_sftp' for task execution.
[2024-03-18T04:29:33.319+0000] {sftp.py:80} INFO - Poking for /path/to/monitor, with pattern 
[2024-03-18T04:29:33.333+0000] {ssh.py:301} WARNING - No Host Key Verification. This won't protect against Man-In-The-Middle attacks
[2024-03-18T04:29:33.596+0000] {transport.py:1909} INFO - Connected (version 2.0, client OpenSSH_8.9p1)
[2024-03-18T04:29:34.158+0000] {transport.py:1909} INFO - Authentication (password) successful!
[2024-03-18T04:29:34.367+0000] {sftp.py:169} INFO - [chan 0] Opened sftp connection (server version 3)
[2024-03-18T04:29:34.377+0000] {sftp.py:169} INFO - [chan 0] sftp session closed.
[2024-03-18T04:30:24.806+0000] {base.py:83} INFO - Using connection ID 'source_sftp' for task execution.
[2024-03-18T04:30:25.268+0000] {sftp.py:80} INFO - Poking for /path/to/monitor, with pattern 
[2024-03-18T04:30:25.410+0000] {ssh.py:301} WARNING - No Host Key Verification. This won't protect against Man-In-The-Middle attacks
[2024-03-18T04:30:26.523+0000] {transport.py:1909} INFO - Connected (version 2.0, client OpenSSH_8.9p1)
[2024-03-18T04:30:28.599+0000] {transport.py:1909} INFO - Authentication (password) successful!
[2024-03-18T04:30:29.248+0000] {sftp.py:169} INFO - [chan 0] Opened sftp connection (server version 3)
[2024-03-18T04:30:29.321+0000] {sftp.py:169} INFO - [chan 0] sftp session closed.
[2024-03-18T04:30:52.823+0000] {local_task_job_runner.py:302} WARNING - State of this instance has been externally set to None. Terminating instance.
[2024-03-18T04:30:52.910+0000] {process_utils.py:131} INFO - Sending 15 to group 102. PIDs of all processes in the group: [102]
[2024-03-18T04:30:52.912+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 102
[2024-03-18T04:30:52.943+0000] {taskinstance.py:2483} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-03-18T04:30:53.130+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/sftp/sensors/sftp.py", line 154, in execute
    return super().execute(context=context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/base.py", line 293, in execute
    time.sleep(self._get_next_poke_interval(started_at, run_duration, try_number))
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2485, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2024-03-18T04:30:53.176+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=sftp_sync, task_id=sftp_sensor_task, execution_date=20240318T042923, start_date=20240318T042931, end_date=20240318T043053
[2024-03-18T04:30:53.310+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 25 for task sftp_sensor_task ((psycopg2.errors.ForeignKeyViolation) insert or update on table "task_fail" violates foreign key constraint "task_fail_ti_fkey"
DETAIL:  Key (dag_id, task_id, run_id, map_index)=(sftp_sync, sftp_sensor_task, manual__2024-03-18T04:29:23.459078+00:00, -1) is not present in table "task_instance".

[SQL: INSERT INTO task_fail (task_id, dag_id, run_id, map_index, start_date, end_date, duration) VALUES (%(task_id)s, %(dag_id)s, %(run_id)s, %(map_index)s, %(start_date)s, %(end_date)s, %(duration)s) RETURNING task_fail.id]
[parameters: {'task_id': 'sftp_sensor_task', 'dag_id': 'sftp_sync', 'run_id': 'manual__2024-03-18T04:29:23.459078+00:00', 'map_index': -1, 'start_date': datetime.datetime(2024, 3, 18, 4, 29, 31, 826397, tzinfo=Timezone('UTC')), 'end_date': datetime.datetime(2024, 3, 18, 4, 30, 53, 169693, tzinfo=Timezone('UTC')), 'duration': 81}]
(Background on this error at: https://sqlalche.me/e/14/gkpj); 102)
[2024-03-18T04:30:53.399+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=102, status='terminated', exitcode=1, started='04:29:31') (102) terminated with exit code 1
