[2024-03-15T09:48:45.355+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: example_sensors.timeout_after_second_date_in_the_future manual__2024-03-15T09:46:41.562323+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
